# Generated by Django 4.0.5 on 2022-08-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('escuderias', models.CharField(choices=[('Ferrari', 'Ferrari'), ('Mercedes', 'Mercedes'), ('Alpine', 'Alpine'), ('Haas', 'Haas'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Alphatauri', 'Alphatauri'), ('Williams', 'Williams'), ('Red Bull', 'Red Bull'), ('Mclaren', 'Mclaren')], default='Alfa Romeo', max_length=20)),
                ('piloto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuito', models.CharField(choices=[('GP de Bahrein', 'GP de Bahrein'), ('GP de Arabia Saudí', 'GP de Arabia Saudí'), ('GP de Australia', 'GP de Australia'), ('GP de Emilia-Romagna', 'GP de Emilia-Romagna'), ('GP de Miami', 'GP de Miami'), ('GP de España', 'GP de España'), ('GP de Mónaco', 'GP de Mónaco'), ('GP de Azerbaiyán', 'GP de Azerbaiyán'), ('GP de Canadá', 'GP de Canadá'), ('GP de Gran Bretaña', 'GP de Gran Bretaña'), ('GP de Austria', 'GP de Austria'), ('GP de Francia', 'GP de Francia'), ('GP de Hungría', 'GP de Hungría'), ('GP de Bélgica', 'GP de Bélgica'), ('GP de Países Bajos', 'GP de Países Bajos'), ('GP de Italia', 'GP de Italia'), ('GP de Singapur', 'GP de Singapur'), ('GP de Japón', 'GP de Japón'), ('GP de EE UU', 'GP de EE UU'), ('GP de Ciudad de México', 'GP de Ciudad de México'), ('GP de Sao Paulo', 'GP de Sao Paulo'), ('GP de Abu Dhabi', 'GP de Abu Dhabi')], default='GP de Sao Paulo', max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_Nacimiento', models.DateField()),
            ],
        ),
    ]
