# Generated by Django 4.0.5 on 2022-08-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='escuderias',
            field=models.CharField(max_length=30),
        ),
    ]
