# Generated by Django 4.0.5 on 2022-08-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoWeb', '0002_alter_autos_escuderias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='escuderias',
            field=models.CharField(choices=[('Ferrari', 'Ferrari'), ('Mercedes', 'Mercedes'), ('Alpine', 'Alpine'), ('Haas', 'Haas'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Alphatauri', 'Alphatauri'), ('Williams', 'Williams'), ('Red Bull', 'Red Bull'), ('Mclaren', 'Mclaren')], default='Alfa Romeo', max_length=30),
        ),
    ]
